emart.wallet=C:/Users/Avaneesh/OneDrive/UCSB_Classes/Spring2026/CS174A/Project/Wallet_CS174AProject
emart.password=3e6vF#5qw#9DP_$
emart.tns=cs174aproject_tp

depot.wallet=C:/Users/Avaneesh/OneDrive/UCSB_Classes/Spring2026/CS174A/Project/Wallet_cs174db
depot.password=LexusCar2023!
depot.tns=cs174db_low